
package com.ofss.fcubs.service.fcubsldservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FCUBSLDService", targetNamespace = "http://types.ws.gw.fcubs.ofss.com", wsdlLocation = "file:/C:/Users/aojinadu/AppData/Local/Temp/2/tempdir7483968708482935288.tmp/FCUBSLDService_1.wsdl")
public class FCUBSLDService
    extends Service
{

    private final static URL FCUBSLDSERVICE_WSDL_LOCATION;
    private final static WebServiceException FCUBSLDSERVICE_EXCEPTION;
    private final static QName FCUBSLDSERVICE_QNAME = new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSLDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/aojinadu/AppData/Local/Temp/2/tempdir7483968708482935288.tmp/FCUBSLDService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSLDSERVICE_WSDL_LOCATION = url;
        FCUBSLDSERVICE_EXCEPTION = e;
    }

    public FCUBSLDService() {
        super(__getWsdlLocation(), FCUBSLDSERVICE_QNAME);
    }

    public FCUBSLDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSLDSERVICE_QNAME, features);
    }

    public FCUBSLDService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSLDSERVICE_QNAME);
    }

    public FCUBSLDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSLDSERVICE_QNAME, features);
    }

    public FCUBSLDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSLDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSLDServiceSEI
     */
    @WebEndpoint(name = "FCUBSLDServiceSEI")
    public FCUBSLDServiceSEI getFCUBSLDServiceSEI() {
        return super.getPort(new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSLDServiceSEI"), FCUBSLDServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSLDServiceSEI
     */
    @WebEndpoint(name = "FCUBSLDServiceSEI")
    public FCUBSLDServiceSEI getFCUBSLDServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSLDServiceSEI"), FCUBSLDServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSLDSERVICE_EXCEPTION!= null) {
            throw FCUBSLDSERVICE_EXCEPTION;
        }
        return FCUBSLDSERVICE_WSDL_LOCATION;
    }

}
