
package com.ofss.fcubs.service.fcubsldservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FCUBSLDServiceSEI", targetNamespace = "http://types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSLDServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeProductFS")
    @WebResult(name = "AUTHORIZEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZEPRODUCTFSFSRES authorizeProductFS(
        @WebParam(name = "AUTHORIZEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeProductIO")
    @WebResult(name = "AUTHORIZEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZEPRODUCTIOPKRES authorizeProductIO(
        @WebParam(name = "AUTHORIZEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "CreateProductFS")
    @WebResult(name = "CREATEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEPRODUCTFSFSRES createProductFS(
        @WebParam(name = "CREATEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "CreateProductIO")
    @WebResult(name = "CREATEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEPRODUCTIOPKRES createProductIO(
        @WebParam(name = "CREATEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "DeleteProductFS")
    @WebResult(name = "DELETEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEPRODUCTFSFSRES deleteProductFS(
        @WebParam(name = "DELETEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "DeleteProductIO")
    @WebResult(name = "DELETEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEPRODUCTIOPKRES deleteProductIO(
        @WebParam(name = "DELETEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYPRODUCTFSFSRES
     */
    @WebMethod(operationName = "ModifyProductFS")
    @WebResult(name = "MODIFYPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYPRODUCTFSFSRES modifyProductFS(
        @WebParam(name = "MODIFYPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYPRODUCTIOPKRES
     */
    @WebMethod(operationName = "ModifyProductIO")
    @WebResult(name = "MODIFYPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYPRODUCTIOPKRES modifyProductIO(
        @WebParam(name = "MODIFYPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYPRODUCTIOFSRES
     */
    @WebMethod(operationName = "QueryProductIO")
    @WebResult(name = "QUERYPRODUCT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYPRODUCTIOFSRES queryProductIO(
        @WebParam(name = "QUERYPRODUCT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYPRODUCTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZEBRNPRMFSFSRES
     */
    @WebMethod(operationName = "AuthorizeBrnPrmFS")
    @WebResult(name = "AUTHORIZEBRNPRM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZEBRNPRMFSFSRES authorizeBrnPrmFS(
        @WebParam(name = "AUTHORIZEBRNPRM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZEBRNPRMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHLDPAYMENTFSFSRES
     */
    @WebMethod(operationName = "AuthLDPaymentFS")
    @WebResult(name = "AUTHLDPAYMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHLDPAYMENTFSFSRES authLDPaymentFS(
        @WebParam(name = "AUTHLDPAYMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHLDPAYMENTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZELDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeLDContractFS")
    @WebResult(name = "AUTHORIZELDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZELDCONTRACTFSFSRES authorizeLDContractFS(
        @WebParam(name = "AUTHORIZELDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZELDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZELDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeLDContractIO")
    @WebResult(name = "AUTHORIZELDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZELDCONTRACTIOPKRES authorizeLDContractIO(
        @WebParam(name = "AUTHORIZELDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZELDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "CreateLDContractFS")
    @WebResult(name = "CREATELDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDCONTRACTFSFSRES createLDContractFS(
        @WebParam(name = "CREATELDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "CreateLDContractIO")
    @WebResult(name = "CREATELDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDCONTRACTIOPKRES createLDContractIO(
        @WebParam(name = "CREATELDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDPAYMENTFSFSRES
     */
    @WebMethod(operationName = "CreateLDPaymentFS")
    @WebResult(name = "CREATELDPAYMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDPAYMENTFSFSRES createLDPaymentFS(
        @WebParam(name = "CREATELDPAYMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDPAYMENTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDPAYMENTIOPKRES
     */
    @WebMethod(operationName = "CreateLDPaymentIO")
    @WebResult(name = "CREATELDPAYMENT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDPAYMENTIOPKRES createLDPaymentIO(
        @WebParam(name = "CREATELDPAYMENT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDPAYMENTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDPAYMENTSIMFSFSRES
     */
    @WebMethod(operationName = "CreateLDPaymentSimFS")
    @WebResult(name = "CREATELDPAYMENTSIM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDPAYMENTSIMFSFSRES createLDPaymentSimFS(
        @WebParam(name = "CREATELDPAYMENTSIM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDPAYMENTSIMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATELDPAYMENTSIMIOPKRES
     */
    @WebMethod(operationName = "CreateLDPaymentSimIO")
    @WebResult(name = "CREATELDPAYMENTSIM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATELDPAYMENTSIMIOPKRES createLDPaymentSimIO(
        @WebParam(name = "CREATELDPAYMENTSIM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATELDPAYMENTSIMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "DeleteLDContractFS")
    @WebResult(name = "DELETELDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDCONTRACTFSFSRES deleteLDContractFS(
        @WebParam(name = "DELETELDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "DeleteLDContractIO")
    @WebResult(name = "DELETELDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDCONTRACTIOPKRES deleteLDContractIO(
        @WebParam(name = "DELETELDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDPAYMENTFSFSRES
     */
    @WebMethod(operationName = "DeleteLDPaymentFS")
    @WebResult(name = "DELETELDPAYMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDPAYMENTFSFSRES deleteLDPaymentFS(
        @WebParam(name = "DELETELDPAYMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDPAYMENTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDPAYMENTIOPKRES
     */
    @WebMethod(operationName = "DeleteLDPaymentIO")
    @WebResult(name = "DELETELDPAYMENT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDPAYMENTIOPKRES deleteLDPaymentIO(
        @WebParam(name = "DELETELDPAYMENT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDPAYMENTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDPAYMENTSIMFSFSRES
     */
    @WebMethod(operationName = "DeleteLDPaymentSimFS")
    @WebResult(name = "DELETELDPAYMENTSIM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDPAYMENTSIMFSFSRES deleteLDPaymentSimFS(
        @WebParam(name = "DELETELDPAYMENTSIM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDPAYMENTSIMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDPAYMENTSIMIOPKRES
     */
    @WebMethod(operationName = "DeleteLDPaymentSimIO")
    @WebResult(name = "DELETELDPAYMENTSIM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDPAYMENTSIMIOPKRES deleteLDPaymentSimIO(
        @WebParam(name = "DELETELDPAYMENTSIM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDPAYMENTSIMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDSIMCONTRACTFSFSRES
     */
    @WebMethod(operationName = "DeleteLDSIMContractFS")
    @WebResult(name = "DELETELDSIMCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDSIMCONTRACTFSFSRES deleteLDSIMContractFS(
        @WebParam(name = "DELETELDSIMCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDSIMCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETELDSIMCONTRACTIOPKRES
     */
    @WebMethod(operationName = "DeleteLDSIMContractIO")
    @WebResult(name = "DELETELDSIMCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETELDSIMCONTRACTIOPKRES deleteLDSIMContractIO(
        @WebParam(name = "DELETELDSIMCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETELDSIMCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDACTIVATESIMULATEFSFSRES
     */
    @WebMethod(operationName = "LDActivateSimulateFS")
    @WebResult(name = "LDACTIVATESIMULATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDACTIVATESIMULATEFSFSRES ldActivateSimulateFS(
        @WebParam(name = "LDACTIVATESIMULATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDACTIVATESIMULATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDACTIVATESIMULATEIOPKRES
     */
    @WebMethod(operationName = "LDActivateSimulateIO")
    @WebResult(name = "LDACTIVATESIMULATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDACTIVATESIMULATEIOPKRES ldActivateSimulateIO(
        @WebParam(name = "LDACTIVATESIMULATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDACTIVATESIMULATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDDELETEVAMIFSFSRES
     */
    @WebMethod(operationName = "LDDeleteVamiFS")
    @WebResult(name = "LDDELETEVAMI_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDDELETEVAMIFSFSRES ldDeleteVamiFS(
        @WebParam(name = "LDDELETEVAMI_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDDELETEVAMIFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDDELETEVAMIIOPKRES
     */
    @WebMethod(operationName = "LDDeleteVamiIO")
    @WebResult(name = "LDDELETEVAMI_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDDELETEVAMIIOPKRES ldDeleteVamiIO(
        @WebParam(name = "LDDELETEVAMI_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDDELETEVAMIIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMIAUTHORIZEFSFSRES
     */
    @WebMethod(operationName = "LDVamiAuthorizeFS")
    @WebResult(name = "LDVAMIAUTHORIZE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMIAUTHORIZEFSFSRES ldVamiAuthorizeFS(
        @WebParam(name = "LDVAMIAUTHORIZE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMIAUTHORIZEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMICONTRACTFSFSRES
     */
    @WebMethod(operationName = "LDVamiContractFS")
    @WebResult(name = "LDVAMICONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMICONTRACTFSFSRES ldVamiContractFS(
        @WebParam(name = "LDVAMICONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMICONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMICONTRACTIOPKRES
     */
    @WebMethod(operationName = "LDVamiContractIO")
    @WebResult(name = "LDVAMICONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMICONTRACTIOPKRES ldVamiContractIO(
        @WebParam(name = "LDVAMICONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMICONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMICREATESIMFSFSRES
     */
    @WebMethod(operationName = "LDVamiCreateSimFS")
    @WebResult(name = "LDVAMICREATESIM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMICREATESIMFSFSRES ldVamiCreateSimFS(
        @WebParam(name = "LDVAMICREATESIM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMICREATESIMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMICREATESIMIOPKRES
     */
    @WebMethod(operationName = "LDVamiCreateSimIO")
    @WebResult(name = "LDVAMICREATESIM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMICREATESIMIOPKRES ldVamiCreateSimIO(
        @WebParam(name = "LDVAMICREATESIM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMICREATESIMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMIDELETESIMFSFSRES
     */
    @WebMethod(operationName = "LDVamiDeleteSimFS")
    @WebResult(name = "LDVAMIDELETESIM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMIDELETESIMFSFSRES ldVamiDeleteSimFS(
        @WebParam(name = "LDVAMIDELETESIM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMIDELETESIMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMIDELETESIMIOPKRES
     */
    @WebMethod(operationName = "LDVamiDeleteSimIO")
    @WebResult(name = "LDVAMIDELETESIM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMIDELETESIMIOPKRES ldVamiDeleteSimIO(
        @WebParam(name = "LDVAMIDELETESIM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMIDELETESIMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDVAMIQUERYSIMIOFSRES
     */
    @WebMethod(operationName = "LDVamiQuerySimIO")
    @WebResult(name = "LDVAMIQUERYSIM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDVAMIQUERYSIMIOFSRES ldVamiQuerySimIO(
        @WebParam(name = "LDVAMIQUERYSIM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDVAMIQUERYSIMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ModifyLDContractFS")
    @WebResult(name = "MODIFYLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYLDCONTRACTFSFSRES modifyLDContractFS(
        @WebParam(name = "MODIFYLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ModifyLDContractIO")
    @WebResult(name = "MODIFYLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYLDCONTRACTIOPKRES modifyLDContractIO(
        @WebParam(name = "MODIFYLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYLDCONTRACTIOFSRES
     */
    @WebMethod(operationName = "QueryLDContractIO")
    @WebResult(name = "QUERYLDCONTRACT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYLDCONTRACTIOFSRES queryLDContractIO(
        @WebParam(name = "QUERYLDCONTRACT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYLDCONTRACTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYLDPAYMENTIOFSRES
     */
    @WebMethod(operationName = "QueryLDPaymentIO")
    @WebResult(name = "QUERYLDPAYMENT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYLDPAYMENTIOFSRES queryLDPaymentIO(
        @WebParam(name = "QUERYLDPAYMENT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYLDPAYMENTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYLDPAYMENTSIMIOFSRES
     */
    @WebMethod(operationName = "QueryLDPaymentSimIO")
    @WebResult(name = "QUERYLDPAYMENTSIM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYLDPAYMENTSIMIOFSRES queryLDPaymentSimIO(
        @WebParam(name = "QUERYLDPAYMENTSIM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYLDPAYMENTSIMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYLDSIMCONTRACTIOFSRES
     */
    @WebMethod(operationName = "QueryLDSIMContractIO")
    @WebResult(name = "QUERYLDSIMCONTRACT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYLDSIMCONTRACTIOFSRES queryLDSIMContractIO(
        @WebParam(name = "QUERYLDSIMCONTRACT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYLDSIMCONTRACTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REASSIGNLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ReassignLDContractFS")
    @WebResult(name = "REASSIGNLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REASSIGNLDCONTRACTFSFSRES reassignLDContractFS(
        @WebParam(name = "REASSIGNLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REASSIGNLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REASSIGNLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ReassignLDContractIO")
    @WebResult(name = "REASSIGNLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REASSIGNLDCONTRACTIOPKRES reassignLDContractIO(
        @WebParam(name = "REASSIGNLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REASSIGNLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSELDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ReverseLDContractFS")
    @WebResult(name = "REVERSELDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSELDCONTRACTFSFSRES reverseLDContractFS(
        @WebParam(name = "REVERSELDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSELDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSELDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ReverseLDContractIO")
    @WebResult(name = "REVERSELDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSELDCONTRACTIOPKRES reverseLDContractIO(
        @WebParam(name = "REVERSELDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSELDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSELDPAYMENTFSFSRES
     */
    @WebMethod(operationName = "ReverseLDPaymentFS")
    @WebResult(name = "REVERSELDPAYMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSELDPAYMENTFSFSRES reverseLDPaymentFS(
        @WebParam(name = "REVERSELDPAYMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSELDPAYMENTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSELDPAYMENTIOPKRES
     */
    @WebMethod(operationName = "ReverseLDPaymentIO")
    @WebResult(name = "REVERSELDPAYMENT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSELDPAYMENTIOPKRES reverseLDPaymentIO(
        @WebParam(name = "REVERSELDPAYMENT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSELDPAYMENTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.ROLLOVERLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "RolloverLDContractFS")
    @WebResult(name = "ROLLOVERLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public ROLLOVERLDCONTRACTFSFSRES rolloverLDContractFS(
        @WebParam(name = "ROLLOVERLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        ROLLOVERLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.ROLLOVERLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "RolloverLDContractIO")
    @WebResult(name = "ROLLOVERLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public ROLLOVERLDCONTRACTIOPKRES rolloverLDContractIO(
        @WebParam(name = "ROLLOVERLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        ROLLOVERLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHFEEACCRUALLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "AuthFeeAccrualLDContractFS")
    @WebResult(name = "AUTHFEEACCRUALLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHFEEACCRUALLDCONTRACTFSFSRES authFeeAccrualLDContractFS(
        @WebParam(name = "AUTHFEEACCRUALLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHFEEACCRUALLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHPROVISIONLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "AuthProvisionLDContractFS")
    @WebResult(name = "AUTHPROVISIONLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHPROVISIONLDCONTRACTFSFSRES authProvisionLDContractFS(
        @WebParam(name = "AUTHPROVISIONLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHPROVISIONLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEFEEACCRUALLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "CreateFeeAccrualLDContractFS")
    @WebResult(name = "CREATEFEEACCRUALLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEFEEACCRUALLDCONTRACTFSFSRES createFeeAccrualLDContractFS(
        @WebParam(name = "CREATEFEEACCRUALLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEFEEACCRUALLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEFEEACCRUALLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "CreateFeeAccrualLDContractIO")
    @WebResult(name = "CREATEFEEACCRUALLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEFEEACCRUALLDCONTRACTIOPKRES createFeeAccrualLDContractIO(
        @WebParam(name = "CREATEFEEACCRUALLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEFEEACCRUALLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEPROVISIONLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "CreateProvisionLDContractFS")
    @WebResult(name = "CREATEPROVISIONLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEPROVISIONLDCONTRACTFSFSRES createProvisionLDContractFS(
        @WebParam(name = "CREATEPROVISIONLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEPROVISIONLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEPROVISIONLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "CreateProvisionLDContractIO")
    @WebResult(name = "CREATEPROVISIONLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEPROVISIONLDCONTRACTIOPKRES createProvisionLDContractIO(
        @WebParam(name = "CREATEPROVISIONLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEPROVISIONLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEFEEACCRUALLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "DeleteFeeAccrualLDContractFS")
    @WebResult(name = "DELETEFEEACCRUALLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEFEEACCRUALLDCONTRACTFSFSRES deleteFeeAccrualLDContractFS(
        @WebParam(name = "DELETEFEEACCRUALLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEFEEACCRUALLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEFEEACCRUALLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "DeleteFeeAccrualLDContractIO")
    @WebResult(name = "DELETEFEEACCRUALLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEFEEACCRUALLDCONTRACTIOPKRES deleteFeeAccrualLDContractIO(
        @WebParam(name = "DELETEFEEACCRUALLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEFEEACCRUALLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDINACTIVATESIMULATEFSFSRES
     */
    @WebMethod(operationName = "LDInactivateSimulateFS")
    @WebResult(name = "LDINACTIVATESIMULATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDINACTIVATESIMULATEFSFSRES ldInactivateSimulateFS(
        @WebParam(name = "LDINACTIVATESIMULATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDINACTIVATESIMULATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.LDINACTIVATESIMULATEIOPKRES
     */
    @WebMethod(operationName = "LDInactivateSimulateIO")
    @WebResult(name = "LDINACTIVATESIMULATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public LDINACTIVATESIMULATEIOPKRES ldInactivateSimulateIO(
        @WebParam(name = "LDINACTIVATESIMULATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        LDINACTIVATESIMULATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYFEEACCRUALLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ModifyFeeAccrualLDContractFS")
    @WebResult(name = "MODIFYFEEACCRUALLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYFEEACCRUALLDCONTRACTFSFSRES modifyFeeAccrualLDContractFS(
        @WebParam(name = "MODIFYFEEACCRUALLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYFEEACCRUALLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYFEEACCRUALLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ModifyFeeAccrualLDContractIO")
    @WebResult(name = "MODIFYFEEACCRUALLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYFEEACCRUALLDCONTRACTIOPKRES modifyFeeAccrualLDContractIO(
        @WebParam(name = "MODIFYFEEACCRUALLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYFEEACCRUALLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYPROVISIONLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ModifyProvisionLDContractFS")
    @WebResult(name = "MODIFYPROVISIONLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYPROVISIONLDCONTRACTFSFSRES modifyProvisionLDContractFS(
        @WebParam(name = "MODIFYPROVISIONLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYPROVISIONLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYPROVISIONLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ModifyProvisionLDContractIO")
    @WebResult(name = "MODIFYPROVISIONLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYPROVISIONLDCONTRACTIOPKRES modifyProvisionLDContractIO(
        @WebParam(name = "MODIFYPROVISIONLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYPROVISIONLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYFEEACCRUALLDCONTRACTIOFSRES
     */
    @WebMethod(operationName = "QueryFeeAccrualLDContractIO")
    @WebResult(name = "QUERYFEEACCRUALLDCONTRACT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYFEEACCRUALLDCONTRACTIOFSRES queryFeeAccrualLDContractIO(
        @WebParam(name = "QUERYFEEACCRUALLDCONTRACT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYFEEACCRUALLDCONTRACTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYPROVISIONLDCONTRACTIOFSRES
     */
    @WebMethod(operationName = "QueryProvisionLDContractIO")
    @WebResult(name = "QUERYPROVISIONLDCONTRACT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYPROVISIONLDCONTRACTIOFSRES queryProvisionLDContractIO(
        @WebParam(name = "QUERYPROVISIONLDCONTRACT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYPROVISIONLDCONTRACTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSEFEEACCRUALLDCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ReverseFeeAccrualLDContractFS")
    @WebResult(name = "REVERSEFEEACCRUALLDCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSEFEEACCRUALLDCONTRACTFSFSRES reverseFeeAccrualLDContractFS(
        @WebParam(name = "REVERSEFEEACCRUALLDCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSEFEEACCRUALLDCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.REVERSEFEEACCRUALLDCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ReverseFeeAccrualLDContractIO")
    @WebResult(name = "REVERSEFEEACCRUALLDCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public REVERSEFEEACCRUALLDCONTRACTIOPKRES reverseFeeAccrualLDContractIO(
        @WebParam(name = "REVERSEFEEACCRUALLDCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        REVERSEFEEACCRUALLDCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.AUTHORIZEBRNPRMIOPKRES
     */
    @WebMethod(operationName = "AuthorizeBrnPrmIO")
    @WebResult(name = "AUTHORIZEBRNPRM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public AUTHORIZEBRNPRMIOPKRES authorizeBrnPrmIO(
        @WebParam(name = "AUTHORIZEBRNPRM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        AUTHORIZEBRNPRMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEBRNPRMFSFSRES
     */
    @WebMethod(operationName = "CreateBrnPrmFS")
    @WebResult(name = "CREATEBRNPRM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEBRNPRMFSFSRES createBrnPrmFS(
        @WebParam(name = "CREATEBRNPRM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEBRNPRMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.CREATEBRNPRMIOPKRES
     */
    @WebMethod(operationName = "CreateBrnPrmIO")
    @WebResult(name = "CREATEBRNPRM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public CREATEBRNPRMIOPKRES createBrnPrmIO(
        @WebParam(name = "CREATEBRNPRM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        CREATEBRNPRMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEBRNPRMFSFSRES
     */
    @WebMethod(operationName = "DeleteBrnPrmFS")
    @WebResult(name = "DELETEBRNPRM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEBRNPRMFSFSRES deleteBrnPrmFS(
        @WebParam(name = "DELETEBRNPRM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEBRNPRMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.DELETEBRNPRMIOPKRES
     */
    @WebMethod(operationName = "DeleteBrnPrmIO")
    @WebResult(name = "DELETEBRNPRM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public DELETEBRNPRMIOPKRES deleteBrnPrmIO(
        @WebParam(name = "DELETEBRNPRM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        DELETEBRNPRMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYBRNPRMFSFSRES
     */
    @WebMethod(operationName = "ModifyBrnPrmFS")
    @WebResult(name = "MODIFYBRNPRM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYBRNPRMFSFSRES modifyBrnPrmFS(
        @WebParam(name = "MODIFYBRNPRM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYBRNPRMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.MODIFYBRNPRMIOPKRES
     */
    @WebMethod(operationName = "ModifyBrnPrmIO")
    @WebResult(name = "MODIFYBRNPRM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public MODIFYBRNPRMIOPKRES modifyBrnPrmIO(
        @WebParam(name = "MODIFYBRNPRM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        MODIFYBRNPRMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsldservice.QUERYBRNPRMIOFSRES
     */
    @WebMethod(operationName = "QueryBrnPrmIO")
    @WebResult(name = "QUERYBRNPRM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "ResponseMsg")
    public QUERYBRNPRMIOFSRES queryBrnPrmIO(
        @WebParam(name = "QUERYBRNPRM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSLDService", partName = "RequestMsg")
        QUERYBRNPRMIOFSREQ requestMsg);

}
