
package com.ofss.fcubs.service.fcubsaccservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FCUBSAccServiceSEI", targetNamespace = "http://types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSAccServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZEACCLASSTFRIOPKRES
     */
    @WebMethod(operationName = "AuthorizeAcClassTfrIO")
    @WebResult(name = "AUTHORIZEACCLASSTFR_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZEACCLASSTFRIOPKRES authorizeAcClassTfrIO(
        @WebParam(name = "AUTHORIZEACCLASSTFR_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZEACCLASSTFRIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZEAUTODEPINSFSFSRES
     */
    @WebMethod(operationName = "AuthorizeAutoDepInsFS")
    @WebResult(name = "AUTHORIZEAUTODEPINS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZEAUTODEPINSFSFSRES authorizeAutoDepInsFS(
        @WebParam(name = "AUTHORIZEAUTODEPINS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZEAUTODEPINSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZEAUTODEPINSIOPKRES
     */
    @WebMethod(operationName = "AuthorizeAutoDepInsIO")
    @WebResult(name = "AUTHORIZEAUTODEPINS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZEAUTODEPINSIOPKRES authorizeAutoDepInsIO(
        @WebParam(name = "AUTHORIZEAUTODEPINS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZEAUTODEPINSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECBSTMTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCbStmtFS")
    @WebResult(name = "AUTHORIZECBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECBSTMTFSFSRES authorizeCbStmtFS(
        @WebParam(name = "AUTHORIZECBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECBSTMTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCbStmtIO")
    @WebResult(name = "AUTHORIZECBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECBSTMTIOPKRES authorizeCbStmtIO(
        @WebParam(name = "AUTHORIZECBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCheckBookFS")
    @WebResult(name = "AUTHORIZECHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHECKBOOKFSFSRES authorizeCheckBookFS(
        @WebParam(name = "AUTHORIZECHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCheckBookIO")
    @WebResult(name = "AUTHORIZECHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHECKBOOKIOPKRES authorizeCheckBookIO(
        @WebParam(name = "AUTHORIZECHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECUSTACCFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCustAccFS")
    @WebResult(name = "AUTHORIZECUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECUSTACCFSFSRES authorizeCustAccFS(
        @WebParam(name = "AUTHORIZECUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECUSTACCIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCustAccIO")
    @WebResult(name = "AUTHORIZECUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECUSTACCIOPKRES authorizeCustAccIO(
        @WebParam(name = "AUTHORIZECUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZETDCUSTACCFSFSRES
     */
    @WebMethod(operationName = "AuthorizeTDCustAccFS")
    @WebResult(name = "AUTHORIZETDCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZETDCUSTACCFSFSRES authorizeTDCustAccFS(
        @WebParam(name = "AUTHORIZETDCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZETDCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZETDCUSTACCIOPKRES
     */
    @WebMethod(operationName = "AuthorizeTDCustAccIO")
    @WebResult(name = "AUTHORIZETDCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZETDCUSTACCIOPKRES authorizeTDCustAccIO(
        @WebParam(name = "AUTHORIZETDCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZETDCUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZETDTOPUPFSFSRES
     */
    @WebMethod(operationName = "AuthorizeTDTopUpFS")
    @WebResult(name = "AUTHORIZETDTOPUP_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZETDTOPUPFSFSRES authorizeTDTopUpFS(
        @WebParam(name = "AUTHORIZETDTOPUP_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZETDTOPUPFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZETDTOPUPIOPKRES
     */
    @WebMethod(operationName = "AuthorizeTDTopUpIO")
    @WebResult(name = "AUTHORIZETDTOPUP_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZETDTOPUPIOPKRES authorizeTDTopUpIO(
        @WebParam(name = "AUTHORIZETDTOPUP_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZETDTOPUPIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CHECKDETAILSQUERYIOFSRES
     */
    @WebMethod(operationName = "CheckDetailsQueryIO")
    @WebResult(name = "CHECKDETAILSQUERY_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CHECKDETAILSQUERYIOFSRES checkDetailsQueryIO(
        @WebParam(name = "CHECKDETAILSQUERY_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CHECKDETAILSQUERYIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSEAUTODEPINSFSFSRES
     */
    @WebMethod(operationName = "CloseAutoDepInsFS")
    @WebResult(name = "CLOSEAUTODEPINS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSEAUTODEPINSFSFSRES closeAutoDepInsFS(
        @WebParam(name = "CLOSEAUTODEPINS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSEAUTODEPINSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSEAUTODEPINSIOPKRES
     */
    @WebMethod(operationName = "CloseAutoDepInsIO")
    @WebResult(name = "CLOSEAUTODEPINS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSEAUTODEPINSIOPKRES closeAutoDepInsIO(
        @WebParam(name = "CLOSEAUTODEPINS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSEAUTODEPINSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECBSTMTFSFSRES
     */
    @WebMethod(operationName = "CloseCbStmtFS")
    @WebResult(name = "CLOSECBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECBSTMTFSFSRES closeCbStmtFS(
        @WebParam(name = "CLOSECBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECBSTMTIOPKRES
     */
    @WebMethod(operationName = "CloseCbStmtIO")
    @WebResult(name = "CLOSECBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECBSTMTIOPKRES closeCbStmtIO(
        @WebParam(name = "CLOSECBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "CloseCheckBookFS")
    @WebResult(name = "CLOSECHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECHECKBOOKFSFSRES closeCheckBookFS(
        @WebParam(name = "CLOSECHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "CloseCheckBookIO")
    @WebResult(name = "CLOSECHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECHECKBOOKIOPKRES closeCheckBookIO(
        @WebParam(name = "CLOSECHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECUSTACCFSFSRES
     */
    @WebMethod(operationName = "CloseCustAccFS")
    @WebResult(name = "CLOSECUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECUSTACCFSFSRES closeCustAccFS(
        @WebParam(name = "CLOSECUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSECUSTACCIOPKRES
     */
    @WebMethod(operationName = "CloseCustAccIO")
    @WebResult(name = "CLOSECUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSECUSTACCIOPKRES closeCustAccIO(
        @WebParam(name = "CLOSECUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSECUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSESTOPPAYMENTSFSFSRES
     */
    @WebMethod(operationName = "CloseStopPaymentsFS")
    @WebResult(name = "CLOSESTOPPAYMENTS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSESTOPPAYMENTSFSFSRES closeStopPaymentsFS(
        @WebParam(name = "CLOSESTOPPAYMENTS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSESTOPPAYMENTSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CLOSESTOPPAYMENTSIOPKRES
     */
    @WebMethod(operationName = "CloseStopPaymentsIO")
    @WebResult(name = "CLOSESTOPPAYMENTS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CLOSESTOPPAYMENTSIOPKRES closeStopPaymentsIO(
        @WebParam(name = "CLOSESTOPPAYMENTS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CLOSESTOPPAYMENTSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATEACCLASSTFRFSFSRES
     */
    @WebMethod(operationName = "CreateAcClassTfrFS")
    @WebResult(name = "CREATEACCLASSTFR_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATEACCLASSTFRFSFSRES createAcClassTfrFS(
        @WebParam(name = "CREATEACCLASSTFR_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATEACCLASSTFRFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATEACCLASSTFRIOPKRES
     */
    @WebMethod(operationName = "CreateAcClassTfrIO")
    @WebResult(name = "CREATEACCLASSTFR_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATEACCLASSTFRIOPKRES createAcClassTfrIO(
        @WebParam(name = "CREATEACCLASSTFR_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATEACCLASSTFRIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATEAUTODEPINSFSFSRES
     */
    @WebMethod(operationName = "CreateAutoDepInsFS")
    @WebResult(name = "CREATEAUTODEPINS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATEAUTODEPINSFSFSRES createAutoDepInsFS(
        @WebParam(name = "CREATEAUTODEPINS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATEAUTODEPINSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATEAUTODEPINSIOPKRES
     */
    @WebMethod(operationName = "CreateAutoDepInsIO")
    @WebResult(name = "CREATEAUTODEPINS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATEAUTODEPINSIOPKRES createAutoDepInsIO(
        @WebParam(name = "CREATEAUTODEPINS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATEAUTODEPINSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECBSTMTFSFSRES
     */
    @WebMethod(operationName = "CreateCbStmtFS")
    @WebResult(name = "CREATECBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECBSTMTFSFSRES createCbStmtFS(
        @WebParam(name = "CREATECBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECBSTMTIOPKRES
     */
    @WebMethod(operationName = "CreateCbStmtIO")
    @WebResult(name = "CREATECBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECBSTMTIOPKRES createCbStmtIO(
        @WebParam(name = "CREATECBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "CreateCheckBookFS")
    @WebResult(name = "CREATECHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECHECKBOOKFSFSRES createCheckBookFS(
        @WebParam(name = "CREATECHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "CreateCheckBookIO")
    @WebResult(name = "CREATECHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECHECKBOOKIOPKRES createCheckBookIO(
        @WebParam(name = "CREATECHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECHQARCHIVALFSFSRES
     */
    @WebMethod(operationName = "CreateChqArchivalFS")
    @WebResult(name = "CREATECHQARCHIVAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECHQARCHIVALFSFSRES createChqArchivalFS(
        @WebParam(name = "CREATECHQARCHIVAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECHQARCHIVALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECHQARCHIVALIOPKRES
     */
    @WebMethod(operationName = "CreateChqArchivalIO")
    @WebResult(name = "CREATECHQARCHIVAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECHQARCHIVALIOPKRES createChqArchivalIO(
        @WebParam(name = "CREATECHQARCHIVAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECHQARCHIVALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECUSTACCFSFSRES
     */
    @WebMethod(operationName = "CreateCustAccFS")
    @WebResult(name = "CREATECUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECUSTACCFSFSRES createCustAccFS(
        @WebParam(name = "CREATECUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATECUSTACCIOPKRES
     */
    @WebMethod(operationName = "CreateCustAccIO")
    @WebResult(name = "CREATECUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATECUSTACCIOPKRES createCustAccIO(
        @WebParam(name = "CREATECUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATECUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATESTOPPAYMENTSFSFSRES
     */
    @WebMethod(operationName = "CreateStopPaymentsFS")
    @WebResult(name = "CREATESTOPPAYMENTS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATESTOPPAYMENTSFSFSRES createStopPaymentsFS(
        @WebParam(name = "CREATESTOPPAYMENTS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATESTOPPAYMENTSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATESTOPPAYMENTSIOPKRES
     */
    @WebMethod(operationName = "CreateStopPaymentsIO")
    @WebResult(name = "CREATESTOPPAYMENTS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATESTOPPAYMENTSIOPKRES createStopPaymentsIO(
        @WebParam(name = "CREATESTOPPAYMENTS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATESTOPPAYMENTSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDCUSTACCFSFSRES
     */
    @WebMethod(operationName = "CreateTDCustAccFS")
    @WebResult(name = "CREATETDCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDCUSTACCFSFSRES createTDCustAccFS(
        @WebParam(name = "CREATETDCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDCUSTACCIOPKRES
     */
    @WebMethod(operationName = "CreateTDCustAccIO")
    @WebResult(name = "CREATETDCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDCUSTACCIOPKRES createTDCustAccIO(
        @WebParam(name = "CREATETDCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDCUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDSIMFSFSRES
     */
    @WebMethod(operationName = "CreateTDSimFS")
    @WebResult(name = "CREATETDSIM_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDSIMFSFSRES createTDSimFS(
        @WebParam(name = "CREATETDSIM_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDSIMFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDSIMIOPKRES
     */
    @WebMethod(operationName = "CreateTDSimIO")
    @WebResult(name = "CREATETDSIM_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDSIMIOPKRES createTDSimIO(
        @WebParam(name = "CREATETDSIM_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDSIMIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDTOPUPFSFSRES
     */
    @WebMethod(operationName = "CreateTDTopUpFS")
    @WebResult(name = "CREATETDTOPUP_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDTOPUPFSFSRES createTDTopUpFS(
        @WebParam(name = "CREATETDTOPUP_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDTOPUPFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.CREATETDTOPUPIOPKRES
     */
    @WebMethod(operationName = "CreateTDTopUpIO")
    @WebResult(name = "CREATETDTOPUP_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public CREATETDTOPUPIOPKRES createTDTopUpIO(
        @WebParam(name = "CREATETDTOPUP_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        CREATETDTOPUPIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETEACCLASSTFRFSFSRES
     */
    @WebMethod(operationName = "DeleteAcClassTfrFS")
    @WebResult(name = "DELETEACCLASSTFR_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETEACCLASSTFRFSFSRES deleteAcClassTfrFS(
        @WebParam(name = "DELETEACCLASSTFR_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETEACCLASSTFRFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETEACCLASSTFRIOPKRES
     */
    @WebMethod(operationName = "DeleteAcClassTfrIO")
    @WebResult(name = "DELETEACCLASSTFR_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETEACCLASSTFRIOPKRES deleteAcClassTfrIO(
        @WebParam(name = "DELETEACCLASSTFR_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETEACCLASSTFRIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETEAUTODEPINSFSFSRES
     */
    @WebMethod(operationName = "DeleteAutoDepInsFS")
    @WebResult(name = "DELETEAUTODEPINS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETEAUTODEPINSFSFSRES deleteAutoDepInsFS(
        @WebParam(name = "DELETEAUTODEPINS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETEAUTODEPINSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETEAUTODEPINSIOPKRES
     */
    @WebMethod(operationName = "DeleteAutoDepInsIO")
    @WebResult(name = "DELETEAUTODEPINS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETEAUTODEPINSIOPKRES deleteAutoDepInsIO(
        @WebParam(name = "DELETEAUTODEPINS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETEAUTODEPINSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECBSTMTFSFSRES
     */
    @WebMethod(operationName = "DeleteCbStmtFS")
    @WebResult(name = "DELETECBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECBSTMTFSFSRES deleteCbStmtFS(
        @WebParam(name = "DELETECBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECBSTMTIOPKRES
     */
    @WebMethod(operationName = "DeleteCbStmtIO")
    @WebResult(name = "DELETECBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECBSTMTIOPKRES deleteCbStmtIO(
        @WebParam(name = "DELETECBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZEACCLASSTFRFSFSRES
     */
    @WebMethod(operationName = "AuthorizeAcClassTfrFS")
    @WebResult(name = "AUTHORIZEACCLASSTFR_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZEACCLASSTFRFSFSRES authorizeAcClassTfrFS(
        @WebParam(name = "AUTHORIZEACCLASSTFR_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZEACCLASSTFRFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHECKDETAILSFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCheckDetailsFS")
    @WebResult(name = "AUTHORIZECHECKDETAILS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHECKDETAILSFSFSRES authorizeCheckDetailsFS(
        @WebParam(name = "AUTHORIZECHECKDETAILS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHECKDETAILSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHECKDETAILSIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCheckDetailsIO")
    @WebResult(name = "AUTHORIZECHECKDETAILS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHECKDETAILSIOPKRES authorizeCheckDetailsIO(
        @WebParam(name = "AUTHORIZECHECKDETAILS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHECKDETAILSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHQARCHIVALFSFSRES
     */
    @WebMethod(operationName = "AuthorizeChqArchivalFS")
    @WebResult(name = "AUTHORIZECHQARCHIVAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHQARCHIVALFSFSRES authorizeChqArchivalFS(
        @WebParam(name = "AUTHORIZECHQARCHIVAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHQARCHIVALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZECHQARCHIVALIOPKRES
     */
    @WebMethod(operationName = "AuthorizeChqArchivalIO")
    @WebResult(name = "AUTHORIZECHQARCHIVAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZECHQARCHIVALIOPKRES authorizeChqArchivalIO(
        @WebParam(name = "AUTHORIZECHQARCHIVAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZECHQARCHIVALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZESTOPPAYMENTSFSFSRES
     */
    @WebMethod(operationName = "AuthorizeStopPaymentsFS")
    @WebResult(name = "AUTHORIZESTOPPAYMENTS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZESTOPPAYMENTSFSFSRES authorizeStopPaymentsFS(
        @WebParam(name = "AUTHORIZESTOPPAYMENTS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZESTOPPAYMENTSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.AUTHORIZESTOPPAYMENTSIOPKRES
     */
    @WebMethod(operationName = "AuthorizeStopPaymentsIO")
    @WebResult(name = "AUTHORIZESTOPPAYMENTS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public AUTHORIZESTOPPAYMENTSIOPKRES authorizeStopPaymentsIO(
        @WebParam(name = "AUTHORIZESTOPPAYMENTS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        AUTHORIZESTOPPAYMENTSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCUSTACCOUNTDETAILSIOFSRES
     */
    @WebMethod(operationName = "QuerycustAccountDetailsIO")
    @WebResult(name = "QUERYCUSTACCOUNTDETAILS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCUSTACCOUNTDETAILSIOFSRES querycustAccountDetailsIO(
        @WebParam(name = "QUERYCUSTACCOUNTDETAILS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCUSTACCOUNTDETAILSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "DeleteCheckBookFS")
    @WebResult(name = "DELETECHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECHECKBOOKFSFSRES deleteCheckBookFS(
        @WebParam(name = "DELETECHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "DeleteCheckBookIO")
    @WebResult(name = "DELETECHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECHECKBOOKIOPKRES deleteCheckBookIO(
        @WebParam(name = "DELETECHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECHQARCHIVALFSFSRES
     */
    @WebMethod(operationName = "DeleteChqArchivalFS")
    @WebResult(name = "DELETECHQARCHIVAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECHQARCHIVALFSFSRES deleteChqArchivalFS(
        @WebParam(name = "DELETECHQARCHIVAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECHQARCHIVALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECHQARCHIVALIOPKRES
     */
    @WebMethod(operationName = "DeleteChqArchivalIO")
    @WebResult(name = "DELETECHQARCHIVAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECHQARCHIVALIOPKRES deleteChqArchivalIO(
        @WebParam(name = "DELETECHQARCHIVAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECHQARCHIVALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECUSTACCFSFSRES
     */
    @WebMethod(operationName = "DeleteCustAccFS")
    @WebResult(name = "DELETECUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECUSTACCFSFSRES deleteCustAccFS(
        @WebParam(name = "DELETECUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETECUSTACCIOPKRES
     */
    @WebMethod(operationName = "DeleteCustAccIO")
    @WebResult(name = "DELETECUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETECUSTACCIOPKRES deleteCustAccIO(
        @WebParam(name = "DELETECUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETECUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETESTOPPAYMENTSFSFSRES
     */
    @WebMethod(operationName = "DeleteStopPaymentsFS")
    @WebResult(name = "DELETESTOPPAYMENTS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETESTOPPAYMENTSFSFSRES deleteStopPaymentsFS(
        @WebParam(name = "DELETESTOPPAYMENTS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETESTOPPAYMENTSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETESTOPPAYMENTSIOPKRES
     */
    @WebMethod(operationName = "DeleteStopPaymentsIO")
    @WebResult(name = "DELETESTOPPAYMENTS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETESTOPPAYMENTSIOPKRES deleteStopPaymentsIO(
        @WebParam(name = "DELETESTOPPAYMENTS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETESTOPPAYMENTSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETETDCUSTACCFSFSRES
     */
    @WebMethod(operationName = "DeleteTDCustAccFS")
    @WebResult(name = "DELETETDCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETETDCUSTACCFSFSRES deleteTDCustAccFS(
        @WebParam(name = "DELETETDCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETETDCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETETDCUSTACCIOPKRES
     */
    @WebMethod(operationName = "DeleteTDCustAccIO")
    @WebResult(name = "DELETETDCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETETDCUSTACCIOPKRES deleteTDCustAccIO(
        @WebParam(name = "DELETETDCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETETDCUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETETDTOPUPFSFSRES
     */
    @WebMethod(operationName = "DeleteTDTopUpFS")
    @WebResult(name = "DELETETDTOPUP_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETETDTOPUPFSFSRES deleteTDTopUpFS(
        @WebParam(name = "DELETETDTOPUP_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETETDTOPUPFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.DELETETDTOPUPIOPKRES
     */
    @WebMethod(operationName = "DeleteTDTopUpIO")
    @WebResult(name = "DELETETDTOPUP_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public DELETETDTOPUPIOPKRES deleteTDTopUpIO(
        @WebParam(name = "DELETETDTOPUP_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        DELETETDTOPUPIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYACCLASSTFRFSFSRES
     */
    @WebMethod(operationName = "ModifyAcClassTfrFS")
    @WebResult(name = "MODIFYACCLASSTFR_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYACCLASSTFRFSFSRES modifyAcClassTfrFS(
        @WebParam(name = "MODIFYACCLASSTFR_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYACCLASSTFRFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYACCLASSTFRIOPKRES
     */
    @WebMethod(operationName = "ModifyAcClassTfrIO")
    @WebResult(name = "MODIFYACCLASSTFR_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYACCLASSTFRIOPKRES modifyAcClassTfrIO(
        @WebParam(name = "MODIFYACCLASSTFR_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYACCLASSTFRIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYAUTODEPINSFSFSRES
     */
    @WebMethod(operationName = "ModifyAutoDepInsFS")
    @WebResult(name = "MODIFYAUTODEPINS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYAUTODEPINSFSFSRES modifyAutoDepInsFS(
        @WebParam(name = "MODIFYAUTODEPINS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYAUTODEPINSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYAUTODEPINSIOPKRES
     */
    @WebMethod(operationName = "ModifyAutoDepInsIO")
    @WebResult(name = "MODIFYAUTODEPINS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYAUTODEPINSIOPKRES modifyAutoDepInsIO(
        @WebParam(name = "MODIFYAUTODEPINS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYAUTODEPINSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCBSTMTFSFSRES
     */
    @WebMethod(operationName = "ModifyCbStmtFS")
    @WebResult(name = "MODIFYCBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCBSTMTFSFSRES modifyCbStmtFS(
        @WebParam(name = "MODIFYCBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCBSTMTIOPKRES
     */
    @WebMethod(operationName = "ModifyCbStmtIO")
    @WebResult(name = "MODIFYCBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCBSTMTIOPKRES modifyCbStmtIO(
        @WebParam(name = "MODIFYCBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "ModifyCheckBookFS")
    @WebResult(name = "MODIFYCHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHECKBOOKFSFSRES modifyCheckBookFS(
        @WebParam(name = "MODIFYCHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "ModifyCheckBookIO")
    @WebResult(name = "MODIFYCHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHECKBOOKIOPKRES modifyCheckBookIO(
        @WebParam(name = "MODIFYCHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHECKDETAILSFSFSRES
     */
    @WebMethod(operationName = "ModifyCheckDetailsFS")
    @WebResult(name = "MODIFYCHECKDETAILS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHECKDETAILSFSFSRES modifyCheckDetailsFS(
        @WebParam(name = "MODIFYCHECKDETAILS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHECKDETAILSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHECKDETAILSIOPKRES
     */
    @WebMethod(operationName = "ModifyCheckDetailsIO")
    @WebResult(name = "MODIFYCHECKDETAILS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHECKDETAILSIOPKRES modifyCheckDetailsIO(
        @WebParam(name = "MODIFYCHECKDETAILS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHECKDETAILSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHQARCHIVALFSFSRES
     */
    @WebMethod(operationName = "ModifyChqArchivalFS")
    @WebResult(name = "MODIFYCHQARCHIVAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHQARCHIVALFSFSRES modifyChqArchivalFS(
        @WebParam(name = "MODIFYCHQARCHIVAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHQARCHIVALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCHQARCHIVALIOPKRES
     */
    @WebMethod(operationName = "ModifyChqArchivalIO")
    @WebResult(name = "MODIFYCHQARCHIVAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCHQARCHIVALIOPKRES modifyChqArchivalIO(
        @WebParam(name = "MODIFYCHQARCHIVAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCHQARCHIVALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCUSTACCFSFSRES
     */
    @WebMethod(operationName = "ModifyCustAccFS")
    @WebResult(name = "MODIFYCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCUSTACCFSFSRES modifyCustAccFS(
        @WebParam(name = "MODIFYCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYCUSTACCIOPKRES
     */
    @WebMethod(operationName = "ModifyCustAccIO")
    @WebResult(name = "MODIFYCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYCUSTACCIOPKRES modifyCustAccIO(
        @WebParam(name = "MODIFYCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYCUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYSTOPPAYMENTSFSFSRES
     */
    @WebMethod(operationName = "ModifyStopPaymentsFS")
    @WebResult(name = "MODIFYSTOPPAYMENTS_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYSTOPPAYMENTSFSFSRES modifyStopPaymentsFS(
        @WebParam(name = "MODIFYSTOPPAYMENTS_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYSTOPPAYMENTSFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYSTOPPAYMENTSIOPKRES
     */
    @WebMethod(operationName = "ModifyStopPaymentsIO")
    @WebResult(name = "MODIFYSTOPPAYMENTS_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYSTOPPAYMENTSIOPKRES modifyStopPaymentsIO(
        @WebParam(name = "MODIFYSTOPPAYMENTS_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYSTOPPAYMENTSIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYTDCUSTACCFSFSRES
     */
    @WebMethod(operationName = "ModifyTDCustAccFS")
    @WebResult(name = "MODIFYTDCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYTDCUSTACCFSFSRES modifyTDCustAccFS(
        @WebParam(name = "MODIFYTDCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYTDCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYTDCUSTACCIOPKRES
     */
    @WebMethod(operationName = "ModifyTDCustAccIO")
    @WebResult(name = "MODIFYTDCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYTDCUSTACCIOPKRES modifyTDCustAccIO(
        @WebParam(name = "MODIFYTDCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYTDCUSTACCIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYTDTOPUPFSFSRES
     */
    @WebMethod(operationName = "ModifyTDTopUpFS")
    @WebResult(name = "MODIFYTDTOPUP_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYTDTOPUPFSFSRES modifyTDTopUpFS(
        @WebParam(name = "MODIFYTDTOPUP_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYTDTOPUPFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.MODIFYTDTOPUPIOPKRES
     */
    @WebMethod(operationName = "ModifyTDTopUpIO")
    @WebResult(name = "MODIFYTDTOPUP_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public MODIFYTDTOPUPIOPKRES modifyTDTopUpIO(
        @WebParam(name = "MODIFYTDTOPUP_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        MODIFYTDTOPUPIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYACCLASSTFRIOFSRES
     */
    @WebMethod(operationName = "QueryAcClassTfrIO")
    @WebResult(name = "QUERYACCLASSTFR_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYACCLASSTFRIOFSRES queryAcClassTfrIO(
        @WebParam(name = "QUERYACCLASSTFR_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYACCLASSTFRIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYACCBALIOFSRES
     */
    @WebMethod(operationName = "QueryAccBalIO")
    @WebResult(name = "QUERYACCBAL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYACCBALIOFSRES queryAccBalIO(
        @WebParam(name = "QUERYACCBAL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYACCBALIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYACCSUMMIOFSRES
     */
    @WebMethod(operationName = "QueryAccSummIO")
    @WebResult(name = "QUERYACCSUMM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYACCSUMMIOFSRES queryAccSummIO(
        @WebParam(name = "QUERYACCSUMM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYACCSUMMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYAUTODEPINSIOFSRES
     */
    @WebMethod(operationName = "QueryAutoDepInsIO")
    @WebResult(name = "QUERYAUTODEPINS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYAUTODEPINSIOFSRES queryAutoDepInsIO(
        @WebParam(name = "QUERYAUTODEPINS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYAUTODEPINSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCBSTMTIOFSRES
     */
    @WebMethod(operationName = "QueryCbStmtIO")
    @WebResult(name = "QUERYCBSTMT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCBSTMTIOFSRES queryCbStmtIO(
        @WebParam(name = "QUERYCBSTMT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCBSTMTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCHECKBOOKIOFSRES
     */
    @WebMethod(operationName = "QueryCheckBookIO")
    @WebResult(name = "QUERYCHECKBOOK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCHECKBOOKIOFSRES queryCheckBookIO(
        @WebParam(name = "QUERYCHECKBOOK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCHECKBOOKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCHECKDETAILSIOFSRES
     */
    @WebMethod(operationName = "QueryCheckDetailsIO")
    @WebResult(name = "QUERYCHECKDETAILS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCHECKDETAILSIOFSRES queryCheckDetailsIO(
        @WebParam(name = "QUERYCHECKDETAILS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCHECKDETAILSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCHQARCHIVALIOFSRES
     */
    @WebMethod(operationName = "QueryChqArchivalIO")
    @WebResult(name = "QUERYCHQARCHIVAL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCHQARCHIVALIOFSRES queryChqArchivalIO(
        @WebParam(name = "QUERYCHQARCHIVAL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCHQARCHIVALIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCUSTACCIOFSRES
     */
    @WebMethod(operationName = "QueryCustAccIO")
    @WebResult(name = "QUERYCUSTACC_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCUSTACCIOFSRES queryCustAccIO(
        @WebParam(name = "QUERYCUSTACC_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCUSTACCIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYCUSTACCBALANCEIOFSRES
     */
    @WebMethod(operationName = "QueryCustAccBalanceIO")
    @WebResult(name = "QUERYCUSTACCBALANCE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYCUSTACCBALANCEIOFSRES queryCustAccBalanceIO(
        @WebParam(name = "QUERYCUSTACCBALANCE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYCUSTACCBALANCEIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYGENADVICEIOFSRES
     */
    @WebMethod(operationName = "QueryGenAdviceIO")
    @WebResult(name = "QUERYGENADVICE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYGENADVICEIOFSRES queryGenAdviceIO(
        @WebParam(name = "QUERYGENADVICE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYGENADVICEIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYSTOPPAYMENTSIOFSRES
     */
    @WebMethod(operationName = "QueryStopPaymentsIO")
    @WebResult(name = "QUERYSTOPPAYMENTS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYSTOPPAYMENTSIOFSRES queryStopPaymentsIO(
        @WebParam(name = "QUERYSTOPPAYMENTS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYSTOPPAYMENTSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYTDCUSTACCIOFSRES
     */
    @WebMethod(operationName = "QueryTDCustAccIO")
    @WebResult(name = "QUERYTDCUSTACC_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYTDCUSTACCIOFSRES queryTDCustAccIO(
        @WebParam(name = "QUERYTDCUSTACC_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYTDCUSTACCIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYTDCUSTACCSIMIOFSRES
     */
    @WebMethod(operationName = "QueryTDCustAccSimIO")
    @WebResult(name = "QUERYTDCUSTACCSIM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYTDCUSTACCSIMIOFSRES queryTDCustAccSimIO(
        @WebParam(name = "QUERYTDCUSTACCSIM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYTDCUSTACCSIMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYTDTOPUPIOFSRES
     */
    @WebMethod(operationName = "QueryTDTopUpIO")
    @WebResult(name = "QUERYTDTOPUP_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYTDTOPUPIOFSRES queryTDTopUpIO(
        @WebParam(name = "QUERYTDTOPUP_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYTDTOPUPIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.QUERYTOPUPSIMIOFSRES
     */
    @WebMethod(operationName = "QueryTopUpSimIO")
    @WebResult(name = "QUERYTOPUPSIM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public QUERYTOPUPSIMIOFSRES queryTopUpSimIO(
        @WebParam(name = "QUERYTOPUPSIM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        QUERYTOPUPSIMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCBSTMTFSFSRES
     */
    @WebMethod(operationName = "ReopenCbStmtFS")
    @WebResult(name = "REOPENCBSTMT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCBSTMTFSFSRES reopenCbStmtFS(
        @WebParam(name = "REOPENCBSTMT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCBSTMTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCBSTMTIOPKRES
     */
    @WebMethod(operationName = "ReopenCbStmtIO")
    @WebResult(name = "REOPENCBSTMT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCBSTMTIOPKRES reopenCbStmtIO(
        @WebParam(name = "REOPENCBSTMT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCBSTMTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCHECKBOOKFSFSRES
     */
    @WebMethod(operationName = "ReopenCheckBookFS")
    @WebResult(name = "REOPENCHECKBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCHECKBOOKFSFSRES reopenCheckBookFS(
        @WebParam(name = "REOPENCHECKBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCHECKBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCHECKBOOKIOPKRES
     */
    @WebMethod(operationName = "ReopenCheckBookIO")
    @WebResult(name = "REOPENCHECKBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCHECKBOOKIOPKRES reopenCheckBookIO(
        @WebParam(name = "REOPENCHECKBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCHECKBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCUSTACCFSFSRES
     */
    @WebMethod(operationName = "ReopenCustAccFS")
    @WebResult(name = "REOPENCUSTACC_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCUSTACCFSFSRES reopenCustAccFS(
        @WebParam(name = "REOPENCUSTACC_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCUSTACCFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsaccservice.REOPENCUSTACCIOPKRES
     */
    @WebMethod(operationName = "ReopenCustAccIO")
    @WebResult(name = "REOPENCUSTACC_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "ResponseMsg")
    public REOPENCUSTACCIOPKRES reopenCustAccIO(
        @WebParam(name = "REOPENCUSTACC_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSAccService", partName = "RequestMsg")
        REOPENCUSTACCIOPKREQ requestMsg);

}
